CREATE TABLE [ELT].[IngestInstance](
	[IngestInstanceID] [int] IDENTITY(1,1) NOT NULL,
	[IngestID] [int] NOT NULL,
	[SourceFileDropFileSystem] [varchar](50) NULL,
	[SourceFileDropFolder] [varchar](200) NULL,
	[SourceFileDropFile] [varchar](200) NULL,
	[DestinationRawFileSystem] [varchar](50) NOT NULL,
	[DestinationRawFolder] [varchar](200) NOT NULL,
	[DestinationRawFile] [varchar](200) NOT NULL,
	[DataFromTimestamp] [datetime2](7) NULL,
	[DataToTimestamp] [datetime2](7) NULL,
	[DataFromNumber] [int] NULL,
	[DataToNumber] [int] NULL,
	[SourceCount] [int] NULL,
	[IngestCount] [int] NULL,
	[IngestStartTimestamp] [datetime] NULL,
	[IngestEndTimestamp] [datetime] NULL,
	[IngestStatus] [varchar](20) NULL,
	[RetryCount] [int] NULL,
	[ReloadFlag] [bit] NULL,
	[CreatedBy] [nvarchar](128) NOT NULL,
	[CreatedTimestamp] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](128) NULL,
	[ModifiedTimestamp] [datetime] NULL,
	[ADFIngestPipelineRunID] [uniqueidentifier] NULL)