CREATE TABLE [ELT].[L1TransformInstance](
	[L1TransformInstanceID] [int] IDENTITY(1,1) NOT NULL,
	[L1TransformID] [int] NOT NULL,
	[IngestInstanceID] [int] NULL,
	[IngestID] [int] NOT NULL,
	[NotebookName] [varchar](100) NULL,
	[NotebookPath] [varchar](200) NULL,
	[CustomParameters] [varchar](max) NULL,
	[InputRawFileSystem] [varchar](50) NOT NULL,
	[InputRawFileFolder] [varchar](200) NOT NULL,
	[InputRawFile] [varchar](200) NOT NULL,
	[InputRawFileDelimiter] [char](1) NULL,
	[InputFileHeaderFlag] [bit] NULL,
	[OutputEntityFileSystem] [varchar](50) NOT NULL,
	[OutputEntityFolder] [varchar](200) NOT NULL,
	[LookupColumns] [varchar](4000) NULL,
	[OutputEntityName] [varchar](200) NULL,
	[OutputEntityWriteMode] [varchar](20) NULL,
	[IngestCount] [int] NULL,
	[L1TransformCount] [int] NULL,
	[L1TransformStartTimestamp] [datetime] NULL,
	[L1TransformEndTimestamp] [datetime] NULL,
	[L1TransformStatus] [varchar](20) NULL,
	[RetryCount] [int] NULL,
	[ActiveFlag] [bit] NOT NULL,
	[ReRunL1TransformFlag] [bit] NULL,
	[IngestADFPipelineRunID] [uniqueidentifier] NULL,
	[L1TransformADFPipelineRunID] [uniqueidentifier] NULL,
	[CreatedBy] [nvarchar](128) NOT NULL,
	[CreatedTimestamp] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](128) NULL,
	[ModifiedTimestamp] [datetime] NULL)