CREATE TABLE [ELT].[L1TransformDefinition](
	[L1TransformID] [int] IDENTITY(1,1) NOT NULL,
	[IngestID] [int] NOT NULL,
	[NotebookPath] [varchar](200) NULL,
	[NotebookName] [varchar](100) NULL,
	[CustomParameters] [varchar](max) NULL,
	[InputRawFileSystem] [varchar](50) NOT NULL,
	[InputRawFileFolder] [varchar](200) NOT NULL,
	[InputRawFile] [varchar](200) NOT NULL,
	[InputRawFileDelimiter] [char](1) NULL,
	[InputFileHeaderFlag] [bit] NULL,
	[OutputEntityFileSystem] [varchar](50) NOT NULL,
	[OutputEntityFolder] [varchar](200) NOT NULL,
	[LookupColumns] [varchar](4000) NULL,
	[OutputEntityName] [varchar](200) NULL,
	[OutputEntityWriteMode] [varchar](20) NULL,
	[MaxRetries] [int] NULL,
	[WatermarkName] [varchar](50) NULL,
	[ActiveFlag] [bit] NOT NULL,
	[CreatedBy] [nvarchar](128) NOT NULL,
	[CreatedTimestamp] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](128) NULL,
	[ModifiedTimestamp] [datetime] NULL)