CREATE TABLE [ELT].[L2TransformInstance](
	[L2TransformInstanceID] [int] IDENTITY(1,1) NOT NULL,
	[L2TransformID] [int] NULL,
	[IngestID] [int] NULL,
	[L1TransformID] [int] NULL,
	[NotebookPath] [varchar](200) NULL,
	[NotebookName] [varchar](100) NULL,
	[CustomParameters] [varchar](max) NULL,
	[InputFileSystem] [varchar](50) NULL,
	[InputFileFolder] [varchar](200) NULL,
	[InputFile] [varchar](200) NULL,
	[InputFileDelimiter] [char](1) NULL,
	[InputFileHeaderFlag] [bit] NULL,
	[InputEntityName] [varchar](200) NULL,
	[WatermarkName] [varchar](50) NULL,
	[DataFromTimestamp] [datetime2](7) NULL,
	[DataToTimestamp] [datetime2](7) NULL,
	[DataFromNumber] [int] NULL,
	[DataToNumber] [int] NULL,
	[OutputL2CurateFileSystem] [varchar](50) NULL,
	[OutputL2CuratedFolder] [varchar](200) NULL,
	[OutputL2CuratedFile] [varchar](200) NULL,
	[OutputL2CuratedFileDelimiter] [char](1) NULL,
	[OutputL2CuratedFileFormat] [varchar](10) NULL,
	[OutputL2CuratedFileWriteMode] [varchar](20) NULL,
	[OutputEntityName] [varchar](200) NULL,
	[OutputEntityFileSystem] [varchar](20) NULL,
	[OutputEntityFolder] [varchar](200) NULL,
	[OutputEntityWriteMode] [varchar](20) NULL,
	[LookupColumns] [varchar](4000) NULL,
	[InputCount] [int] NULL,
	[L2TransformCount] [int] NULL,
	[L2TransformStartTimestamp] [datetime] NULL,
	[L2TransformEndTimestamp] [datetime] NULL,
	[L2TransformStatus] [varchar](20) NULL,
	[RetryCount] [int] NULL,
	[ActiveFlag] [bit] NOT NULL,
	[ReRunL2TransformFlag] [bit] NULL,
	[IngestADFPipelineRunID] [uniqueidentifier] NULL,
	[L1TransformADFPipelineRunID] [uniqueidentifier] NULL,
	[L2TransformADFPipelineRunID] [uniqueidentifier] NULL,
	[CreatedBy] [nvarchar](128) NOT NULL,
	[CreatedTimestamp] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](128) NULL,
	[ModifiedTimestamp] [datetime] NULL)