CREATE TABLE [ELT].[L2TransformDefinition](
	[L2TransformID] [int] IDENTITY(1,1) NOT NULL,
	[IngestID] [int] NULL,
	[L1TransformID] [int] NULL,
	[NotebookPath] [varchar](200) NULL,
	[NotebookName] [varchar](100) NULL,
	[CustomParameters] [varchar](max) NULL,
	[InputType] [varchar](15) NULL,
	[InputFileSystem] [varchar](50) NULL,
	[InputFileFolder] [varchar](200) NULL,
	[InputFile] [varchar](200) NULL,
	[InputFileDelimiter] [char](1) NULL,
	[InputFileHeaderFlag] [bit] NULL,
	[InputEntityName] [varchar](200) NULL,
	[WatermarkName] [varchar](50) NULL,
	[LastWatermarkDate] [datetime2](7) NULL,
	[LastWatermarkNumber] [int] NULL,
	[MaxIntervalMinutes] [int] NULL,
	[MaxIntervalNumber] [int] NULL,
	[MaxRetries] [int] NULL,
	[OutputL2CurateFileSystem] [varchar](50) NULL,
	[OutputL2CuratedFolder] [varchar](200) NULL,
	[OutputL2CuratedFile] [varchar](200) NULL,
	[OutputL2CuratedFileDelimiter] [char](1) NULL,
	[OutputL2CuratedFileFormat] [varchar](10) NULL,
	[OutputL2CuratedFileWriteMode] [varchar](20) NULL,
	[OutputEntityName] [varchar](200) NULL,
	[OutputEntityFileSystem] [varchar](50) NULL,
	[OutputEntityFolder] [varchar](200) NULL,
	[OutputEntityWriteMode] [varchar](20) NOT NULL,
	[LookupColumns] [varchar](4000) NULL,
	[ActiveFlag] [bit] NOT NULL,
	[RunSequence] [int] NOT NULL,
	[CreatedBy] [nvarchar](128) NOT NULL,
	[CreatedTimestamp] [datetime] NOT NULL,
	[ModifiedBy] [nvarchar](128) NULL,
	[ModifiedTimestamp] [datetime] NULL)